-- Seed: 12 promoções publicadas para feed inicial
INSERT INTO promotion (id, slug, title, url, normalized_url, description, normalized_description, current_price, original_price, coupon_code, image_url, status, availability, store_id, created_date, created_at, updated_at, published_at)
VALUES
(gen_random_uuid(), 'smart-tv-43-polegadas-com-desconto', 'Smart TV 43 polegadas com desconto',
 'https://example.com/produtos/smart-tv-43', 'example.com/produtos/smart-tv-43',
 'Smart TV 43 polegadas LED com resolução Full HD, Wi-Fi integrado e sistema operacional inteligente.',
 'smart tv 43 polegadas led com resolucao full hd wifi integrado e sistema operacional inteligente',
 1299.00, 1899.00, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'amazon'),
 CURRENT_DATE, now() - INTERVAL '2 hours', now() - INTERVAL '1 hour', now() - INTERVAL '1 hour'),

(gen_random_uuid(), 'fone-bluetooth-com-estojo-de-carregamento', 'Fone Bluetooth com estojo de carregamento',
 'https://example.com/produtos/fone-bluetooth', 'example.com/produtos/fone-bluetooth',
 'Fone de ouvido Bluetooth 5.3 com cancelamento de ruído e estojo de carregamento incluso.',
 'fone de ouvido bluetooth 53 com cancelamento de ruido e estojo de carregamento incluso',
 149.90, 249.90, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'mercado-livre'),
 CURRENT_DATE, now() - INTERVAL '3 hours', now() - INTERVAL '2 hours', now() - INTERVAL '2 hours'),

(gen_random_uuid(), 'notebook-para-estudos-e-trabalho', 'Notebook para estudos e trabalho',
 'https://example.com/produtos/notebook-estudos', 'example.com/produtos/notebook-estudos',
 'Notebook 15.6 polegadas com processador moderno, 8GB RAM e SSD 256GB para uso diário.',
 'notebook 156 polegadas com processador moderno 8gb ram e ssd 256gb para uso diario',
 2499.00, 3299.00, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'magalu'),
 CURRENT_DATE, now() - INTERVAL '4 hours', now() - INTERVAL '3 hours', now() - INTERVAL '3 hours'),

(gen_random_uuid(), 'air-fryer-familia', 'Air fryer família',
 'https://example.com/produtos/air-fryer-familia', 'example.com/produtos/air-fryer-familia',
 'Air fryer com capacidade de 5 litros, ideal para toda a família, painel digital.',
 'air fryer com capacidade de 5 litros ideal para toda a familia painel digital',
 299.90, 499.90, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'amazon'),
 CURRENT_DATE, now() - INTERVAL '5 hours', now() - INTERVAL '4 hours', now() - INTERVAL '4 hours'),

(gen_random_uuid(), 'cafeteira-eletrica-compacta', 'Cafeteira elétrica compacta',
 'https://example.com/produtos/cafeteira-compacta', 'example.com/produtos/cafeteira-compacta',
 'Cafeteira elétrica compacta para até 15 xícaras com jarra de vidro temperado.',
 'cafeteira eletrica compacta para ate 15 xicaras com jarra de vidro temperado',
 89.90, 149.90, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'UNKNOWN', (SELECT id FROM store WHERE slug = 'mercado-livre'),
 CURRENT_DATE, now() - INTERVAL '6 hours', now() - INTERVAL '5 hours', now() - INTERVAL '5 hours'),

(gen_random_uuid(), 'monitor-24-polegadas-full-hd', 'Monitor 24 polegadas Full HD',
 'https://example.com/produtos/monitor-24-fhd', 'example.com/produtos/monitor-24-fhd',
 'Monitor 24 polegadas IPS Full HD com taxa de atualização de 75Hz e bordas finas.',
 'monitor 24 polegadas ips full hd com taxa de atualizacao de 75hz e bordas finas',
 649.00, 899.00, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'magalu'),
 CURRENT_DATE, now() - INTERVAL '7 hours', now() - INTERVAL '6 hours', now() - INTERVAL '6 hours'),

(gen_random_uuid(), 'mouse-sem-fio', 'Mouse sem fio',
 'https://example.com/produtos/mouse-sem-fio', 'example.com/produtos/mouse-sem-fio',
 'Mouse sem fio ergonômico com sensor óptico de alta precisão e bateria de longa duração.',
 'mouse sem fio ergonomico com sensor optico de alta precisao e bateria de longa duracao',
 59.90, 99.90, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'amazon'),
 CURRENT_DATE, now() - INTERVAL '8 hours', now() - INTERVAL '7 hours', now() - INTERVAL '7 hours'),

(gen_random_uuid(), 'teclado-mecanico-compacto', 'Teclado mecânico compacto',
 'https://example.com/produtos/teclado-mecanico', 'example.com/produtos/teclado-mecanico',
 'Teclado mecânico compacto 60% com switches blue e iluminação RGB por tecla.',
 'teclado mecanico compacto 60 com switches blue e iluminacao rgb por tecla',
 199.90, 329.90, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'UNKNOWN', (SELECT id FROM store WHERE slug = 'mercado-livre'),
 CURRENT_DATE, now() - INTERVAL '9 hours', now() - INTERVAL '8 hours', now() - INTERVAL '8 hours'),

(gen_random_uuid(), 'panela-de-pressao-eletrica', 'Panela de pressão elétrica',
 'https://example.com/produtos/panela-pressao-eletrica', 'example.com/produtos/panela-pressao-eletrica',
 'Panela de pressão elétrica multifuncional 6 litros com 12 programas de cozimento.',
 'panela de pressao eletrica multifuncional 6 litros com 12 programas de cozimento',
 349.90, 549.90, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'magalu'),
 CURRENT_DATE, now() - INTERVAL '10 hours', now() - INTERVAL '9 hours', now() - INTERVAL '9 hours'),

(gen_random_uuid(), 'echo-smart-speaker', 'Echo smart speaker',
 'https://example.com/produtos/echo-speaker', 'example.com/produtos/echo-speaker',
 'Smart speaker com assistente de voz integrada, som de qualidade e controle de casa inteligente.',
 'smart speaker com assistente de voz integrada som de qualidade e controle de casa inteligente',
 249.00, 399.00, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'amazon'),
 CURRENT_DATE, now() - INTERVAL '11 hours', now() - INTERVAL '10 hours', now() - INTERVAL '10 hours'),

(gen_random_uuid(), 'mochila-para-notebook', 'Mochila para notebook',
 'https://example.com/produtos/mochila-notebook', 'example.com/produtos/mochila-notebook',
 'Mochila resistente à água com compartimento acolchoado para notebook de até 15.6 polegadas.',
 'mochila resistente a agua com compartimento acolchoado para notebook de ate 156 polegadas',
 119.90, 189.90, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'UNKNOWN', (SELECT id FROM store WHERE slug = 'mercado-livre'),
 CURRENT_DATE, now() - INTERVAL '12 hours', now() - INTERVAL '11 hours', now() - INTERVAL '11 hours'),

(gen_random_uuid(), 'ssd-1tb', 'SSD 1TB',
 'https://example.com/produtos/ssd-1tb', 'example.com/produtos/ssd-1tb',
 'SSD interno 1TB com leitura de até 560MB/s e gravação de até 530MB/s, interface SATA III.',
 'ssd interno 1tb com leitura de ate 560mbs e gravacao de ate 530mbs interface sata iii',
 379.00, 549.00, NULL, 'https://placehold.co/600x400?text=DescontoVivo',
 'PUBLISHED', 'AVAILABLE', (SELECT id FROM store WHERE slug = 'magalu'),
 CURRENT_DATE, now() - INTERVAL '13 hours', now() - INTERVAL '12 hours', now() - INTERVAL '12 hours');
